### ISSUE TITLE
Broken link in water level (.md) post

### ISSUE THREAD

**Issue by gracelower** [COAST-Lab/COAST-Lab.github.io#6] opened 2024-06-05 14:26 UTC
Pathway: _posts/2022-07-15-waterLevel.md

Clinking link to "Firmware" provides Error 404: "The main branch of COAST-Lab.github.io does not contain the path _posts/Firmware."

**Comment by SUPScientist** [comment] 2024-06-05 19:42
Great catch. This is an issue caused by copying the file from the original repo (https://github.com/COAST-Lab/Open-Water-Level) to this repo. The original repo uses lots of relative links (e.g., from folder A, go up one folder, then down to the subfolder `Firmware` to find the necessary file/link). However, the website wasn't set up with a subfolder `Firmware`, so it makes sense that that would break! I'll take this one, and thanks for pointing it out!

**Comment by SUPScientist** [comment] 2024-06-05 20:06
Fixed with https://github.com/COAST-Lab/COAST-Lab.github.io/commit/73f04a86722d944e774ac45535378426bb95bfc2

**Closed** 2024-06-05 20:06 UTC
Labels: bug

**Comment by SUPScientist** [comment] 2024-06-05 20:07
@gracelower, check out https://coast-lab.org/waterLevel/ to see if that looks better. I fixed the link tied to this issue so if you see anything else, feel free to open a new issue.
